# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: backend-config
#   namespace: devconnect
# data:
#   MONGODB_URI: mongodb://admin:password123@mongodb:27017/devconnect?authSource=admin
#   JWT_SECRET: 64afc1141e3969877c936171c9548fd3

#command to create configmap: kubectl apply -f backend/configmap.yml
#command to delete configmap: kubectl delete -f backend/configmap.yml
