[local]
localhost ansible_connection=local ansible_python_interpreter="{{ ansible_playbook_python }}"

[eks_admin]
localhost

[eks_admin:vars]
aws_region=ap-south-1
cluster_name=devconnect-cluster
argocd_repo_url=https://github.com/YOUR_USERNAME/DevConnect.git
app_namespace=devconnect
