apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devconnect

resources:
  - ../../namespace.yml
  - ../../base/backend
  - ../../base/database
  - ../../base/frontend
  - ../../base/ingress

images:
  - name: devconnect-backend
    newTag: latest

  - name: devconnect-frontend
    newTag: latest
